### ISSUE TITLE
Validate Card Metadata

### ISSUE THREAD

**Issue by nateraw** [nateraw/modelcards#2]
Card Metadata that comes at the top of the readme between the `---`s should be validated. For example, languages are a list of strings, not a string, so if someone overwrites `card.data['language'] = 'en'` it should be automatically updated to `['en']`. If they try to set it to a weird type, like a float, they should get a helpful error message.

**Comment by nateraw** [comment]
whoops this one shouldn't have been closed, it has only very slightly begun to be resolved with #5 .

**Comment by nateraw** [comment]
As @adrinjalali suggested, we should add a `.validate()` fn in the card data. this should mirror the validation done on the hub server side of things (as suggested by @julienc [here](https://huggingface.co/spaces/nateraw/modelcard-creator/discussions/2)). bonus points if you get same error messages too to help with debugging.

**Comment by julien-c** [comment]
WDYT of calling a server API to perform the validation? that way it's guaranteed to return the same rules forever (even when they involve)

cc @coyotte508

**Comment by coyotte508** [comment]
> WDYT of calling a server API to perform the validation? that way it's guaranteed to return the same rules forever (even when they involve)
> 
> cc @coyotte508

Agreed, similar to the `preupload` API call now available to determine if a file should be LFS (implemented in #888)

**Comment by coyotte508** [comment]
Actually @nateraw you can call `POST /validate-yaml` with in the body:

- `repoType`: `"model"`, `"dataset"` or `"space"`
- `repoId`: `string` - does not have to be an existing repo

It returns either a 200 if there are warnings or nothing, and a 400 if there are validation errors.

The return value is a raw string, for now (unless you'd like something more elaborate). __Please add__ the `Accept: text/plain` header in the request. It will work without for now, but it will help us not break anything later if we make changes. cc @Pierrci

**Comment by adrinjalali** [comment]
I don't think it's a good idea to require internet while creating a modelcard. As a user that would come as a surprise to me. I'd rather have that logic implemented locally.

When working with the hub, internet requirement is reasonable, but that doesn't seem like something we could ask users for creating a model card.

**Comment by coyotte508** [comment]
> I don't think it's a good idea to require internet while creating a modelcard. 

Maybe we could display a message if lack of internet connection (eg "offline mode - model card metadata validation skipped") while still allowing creation if offline.

**Comment by adrinjalali** [comment]
I think we should have the validation offline. If on top of that we want to have an online validation kinda thing, we can have a separate method which the user can explicitly call knowing that they're validating against the server. But even with something line `pypi`, one can run the validation using `twine check` w/o having to upload anything to pypi.

Model card validation on the server side should be very explicit and opt-in, otherwise users will be leaking information to us most of them w/o realizing they're doing it.

**Comment by coyotte508** [comment]
The issue is validation rules will change. (and new values will be accepted for licenses, ...)

On one hand we'd have to continually update the validation on the python side, which we maybe could automate (finding a way for python code & JS code to share logic).

But on the other hand users would need to update their HF library version - or periodically download an updated schema.

All that is possible but much more burdensome to implement IMO.

**Comment by adrinjalali** [comment]
Then we can have a minimal validation logic in the library which should stay stable, and then when/if users upload to the hub, they'll get a meaningful error message which the library can show.

This comes from the fact that we have certain data which is hub specific in the model card, and the hub's backend does things with it. From a user's perspective, a model card should be a mostly free format and this library should help them create a nice one, rather than this library being a place where we help users create some metadata that the hub understands.

Mixing these two together will keep causing us issues.

**Comment by osanseviero** [comment]
> I guess it's not clear to me what this does, then. If it's "just" free form text in sections, what does the library actually do? It's more like a template of a markdown file?

I think this discussion is now mixing the metadata vs rest of the content. The original discussion was about the metadata :) In any case, I would suggest the simpler approach and rather than duplicating (potentially changing) server logic in the library, just manage it through a call to the API. This will help avoid unexpected mismatches and will be easier to maintain.

A big goal of this library is to standardize across the library integrations, so I feel it's ok (even intended) if it has some bindings with the Hub. We have things to push to the Hub, I think metadata validation from the server falls under this scope.

**Comment by nateraw** [comment]
The only time we _really_ have to validate is when pushing to the hub, eh? Because that's when things would break.

So would it make sense to just validate via API call before pushing to the hub and provide nice error message if it breaks? It could still be at `CardData.validate`, but would only be called by the library when pushing to the hub because we can assume they should have internet access for that.
